spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cpt202_schema
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: 13585348990@163.com
    password: YSLKJLHNEIYFYSJD
