package group27.xukai.cpt202b.entity;

public class Notification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notificationId
     *
     * @mbggenerated
     */
    private Integer notificationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.trainer_ID
     *
     * @mbggenerated
     */
    private String planlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.customer_ID
     *
     * @mbggenerated
     */
    private String memberemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notificationId
     *
     * @return the value of notification.notificationId
     *
     * @mbggenerated
     */
    public Integer getNotificationId() {
        return notificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notificationId
     *
     * @param notificationId the value for notification.notificationId
     *
     * @mbggenerated
     */
    public void setNotificationId(Integer notificationId) {
        this.notificationId = notificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.type
     *
     * @return the value of notification.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.type
     *
     * @param type the value for notification.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.trainer_ID
     *
     * @return the value of notification.trainer_ID
     *
     * @mbggenerated
     */
    public String getPlanlevel() {
        return planlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.trainer_ID
     *
     * @param planlevel the value for notification.trainer_ID
     *
     * @mbggenerated
     */
    public void setPlanlevel(String planlevel) {
        this.planlevel = planlevel == null ? null : planlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.customer_ID
     *
     * @return the value of notification.customer_ID
     *
     * @mbggenerated
     */
    public String getMemberemail() {
        return memberemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.customer_ID
     *
     * @param memberemail the value for notification.customer_ID
     *
     * @mbggenerated
     */
    public void setMemberemail(String memberemail) {
        this.memberemail = memberemail == null ? null : memberemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.date
     *
     * @return the value of notification.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.date
     *
     * @param date the value for notification.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.content
     *
     * @return the value of notification.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.content
     *
     * @param content the value for notification.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}